include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/gen/*
    - lib/**/*.g.dart
    - packages/**/*.gen.dart
    - packages/**/*.g.dart
linter:
  rules:
    public_member_api_docs: false
