// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3BGOKfuFKWU1baUfeoBrUJMzwz8O7OyY',
    appId: '1:434649595794:web:5c7b6081e167c359f70b4b',
    messagingSenderId: '434649595794',
    projectId: 'flutter-instagram-clone-3aaa6',
    authDomain: 'flutter-instagram-clone-3aaa6.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-3aaa6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqjwewQ_tdwSFzzHEqMYhjMFyBASjZRjE',
    appId: '1:434649595794:android:6a459b5415c282bcf70b4b',
    messagingSenderId: '434649595794',
    projectId: 'flutter-instagram-clone-3aaa6',
    storageBucket: 'flutter-instagram-clone-3aaa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5oWHCFFKGduQXSZXYFh8Qm94A8bwxrrw',
    appId: '1:434649595794:ios:2a0a9ec7929293bff70b4b',
    messagingSenderId: '434649595794',
    projectId: 'flutter-instagram-clone-3aaa6',
    storageBucket: 'flutter-instagram-clone-3aaa6.firebasestorage.app',
    iosClientId: '434649595794-47ptm2tb5jjoepfeh8b5m2r8v1e75528.apps.googleusercontent.com',
    iosBundleId: 'com.hizenberg.flutterInstagramCloneProd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5oWHCFFKGduQXSZXYFh8Qm94A8bwxrrw',
    appId: '1:434649595794:ios:83e629c48dc813d3f70b4b',
    messagingSenderId: '434649595794',
    projectId: 'flutter-instagram-clone-3aaa6',
    storageBucket: 'flutter-instagram-clone-3aaa6.firebasestorage.app',
    iosClientId: '434649595794-tb3ik8g04ve2bscoh8fsj3al185gk6tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3BGOKfuFKWU1baUfeoBrUJMzwz8O7OyY',
    appId: '1:434649595794:web:2a47eb686abbeeaef70b4b',
    messagingSenderId: '434649595794',
    projectId: 'flutter-instagram-clone-3aaa6',
    authDomain: 'flutter-instagram-clone-3aaa6.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-3aaa6.firebasestorage.app',
  );
}
