// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiFdkJJKwMOgt7EeqnM_DEoRYqODtWTWg',
    appId: '1:33441752748:web:ef53db617901a83cd72109',
    messagingSenderId: '33441752748',
    projectId: 'flutter-instagram-clone-26fef',
    authDomain: 'flutter-instagram-clone-26fef.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-26fef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8033JOiDEtGIFw5kuZ-7tQ_cUNGFcEpc',
    appId: '1:33441752748:android:d15ae3348439cfa6d72109',
    messagingSenderId: '33441752748',
    projectId: 'flutter-instagram-clone-26fef',
    storageBucket: 'flutter-instagram-clone-26fef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp2Fg9tXluI7P2T8b_63m4DsKbFpCbMtI',
    appId: '1:33441752748:ios:bf596cc3fe7c0188d72109',
    messagingSenderId: '33441752748',
    projectId: 'flutter-instagram-clone-26fef',
    storageBucket: 'flutter-instagram-clone-26fef.firebasestorage.app',
    iosClientId: '33441752748-0reaq23ksdhks5k9mhg2skjklq94kcv8.apps.googleusercontent.com',
    iosBundleId: 'com.hizenberg.flutterInstagramCloneDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp2Fg9tXluI7P2T8b_63m4DsKbFpCbMtI',
    appId: '1:33441752748:ios:1c0ce05c24727033d72109',
    messagingSenderId: '33441752748',
    projectId: 'flutter-instagram-clone-26fef',
    storageBucket: 'flutter-instagram-clone-26fef.firebasestorage.app',
    iosClientId: '33441752748-c16ntfneo0a0hhcucjir08n77k2fk0s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiFdkJJKwMOgt7EeqnM_DEoRYqODtWTWg',
    appId: '1:33441752748:web:8048c5e790147850d72109',
    messagingSenderId: '33441752748',
    projectId: 'flutter-instagram-clone-26fef',
    authDomain: 'flutter-instagram-clone-26fef.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-26fef.firebasestorage.app',
  );
}
